# docker compose v2 формат. Используем простую связку: app + db + nginx.
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile  # Явно указываем путь, чтобы показать структуру
    environment:
      # Конфиг через переменные окружения — то же самое перенесём в ConfigMap/Secret в k8s
      APP_ENV: "dev"
      PORT: "5000"
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/appdb"
    depends_on:
      - db
    networks: [appnet]

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks: [appnet]

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8000:80"          # на хосте будет http://localhost:8000
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks: [appnet]

volumes:
  dbdata:

networks:
  appnet:
    driver: bridge
