# Secret: конфиденциальные значения, пример с base64.
# echo -n 'postgresql://postgres:postgres@db:5432/appdb' | base64
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQGRiOjU0MzIvYXBwZGI=
